#!/bin/bash
#PBS -r n
#PBS -o CIG_grid.out
#PBS -e CIG_grid.err
#PBS -m e
#PBS -M bxia@houstonmethodist.org
#PBS -l walltime=96:00:00
#PBS -l nodes=1:ppn=8
#PBS -q mediummem
#PBS -l mem=2000mb
##PBS -q highmem
##PBS -q default

module load python/2.7.11
cd /home/tmhbxx3/archive/CIG_RNA/src/
python real_table.py
#python CIG_GRN.py
#python CIG_best_features.py
#python ./CIG_feature_table.py
#python ./CIG_utils.py
